# Install RVM

---
- hosts: all
  gather_facts: no

  vars:
    ruby_ver: ruby-2.2-head

  tasks:
  - name: Install GPG key
    shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

  - name: Install RVM
    shell: \curl -sSL https://get.rvm.io | bash -s stable --ruby

    name: Source bashrc
    shell: source ~/.bashrc

  - name: Install Ruby 2.2 stable
    shell: rvm install {{ruby_ver}}
    
  - name: Install Ruby 2.2 stable
    shell: rvm --default use {{ruby_ver}}
