# Install RVM

---
- hosts: all
  gather_facts: no

  vars:
    username: clark
    ruby_ver: ruby-2.2-head
    rvm_shell: source /home/{{username}}/.rvm/scripts/rvm &&

  tasks:
  - name: Install GPG key
    shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

  - name: Install RVM
    shell: \curl -sSL https://get.rvm.io | bash -s stable --ruby

  - name: Install Ruby 2.2 stable
    shell: "{{rvm_shell}} rvm install {{ruby_ver}}"

  - name: Install Ruby 2.2 stable
    shell: "{{rvm_shell}} --default use {{ruby_ver}}"
