#!/bin/bash

# creates ssh keys...
# when you create them.
# paste the public one into github or bitbucket.



if [ ! -f $HOME/.ssh/id_rsa ]; then
  echo "> Create SSH keys."
  ssh-keygen -t rsa -C "hubertwwong@gmail.com"
fi
