#!/bin/bash

echo "> Install Add Dropbox key."
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E

echo "> Add to apt."
sudo add-apt-repository "deb http://linux.dropbox.com/ubuntu $(lsb_release -sc) main"

echo "> Install Dropbox."
sudo apt-get update && sudo apt-get install nautilus-dropbox
