#!/bin/bash

# Run thru the wizard
sh -c "$(curl -fsSL http://debian.yeasoft.net/add-btsync-repository.sh)"

# adding sources.
#sudo echo deb http://debian.yeasoft.net/btsync $(lsb_release -cs) main contrib non-free >> /etc/apt/sources.list.d/btsync.list
#sudo echo deb-src http://debian.yeasoft.net/btsync $(lsb_release -cs) main contrib non-free >> /etc/apt/sources.list.d/btsync.list

# install btsync user
#yes | sudo apt-get update
#yes | sudo apt-get install btsync-user

`which sudo` apt-get update
`which sudo` apt-get install btsync-gui

# Source
# http://www.yeasoft.com/site/projects:btsync-deb:btsync-gui
