#!/bin/bash

echo "> Install nvm."
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash

echo "> Install node. This is the latest version."
nvm install node

echo "> Alias node."
nvm alias default node

# https://github.com/creationix/nvm
