#!/bin/bash

# Setting up keys.
sudo gpg --keyserver pgp.mit.edu --recv-keys 6BF18B15
sudo gpg --armor --export 6BF18B15 | sudo apt-key add -

# adding sources.
sudo echo deb http://debian.yeasoft.net/btsync $(lsb_release -cs) main contrib non-free >> /etc/apt/sources.list.d/btsync.list
sudo echo deb-src http://debian.yeasoft.net/btsync $(lsb_release -cs) main contrib non-free >> /etc/apt/sources.list.d/btsync.list

# install btsync user
yes | sudo apt-get update
yes | sudo apt-get install btsync-user

# Source
# https://gist.github.com/zQueal/5692812
