#!/bin/bash

#echo "> Install Add Dropbox key."
#sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E

echo "> Download source."
cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86" | tar xzf -

echo "> Install Dropbox."
sudo apt-get update && sudo apt-get install nautilus-dropbox
