#!/bin/bash

# Install ansible
yes | sudo apt-get -y install software-properties-common
yes | sudo apt-add-repository -y ppa:ansible/ansible
yes | sudo apt-get -y update
yes | sudo apt-get -y install ansible

# move the original config files over if you need it.
sudo mv -n /etc/ansible/hosts /etc/ansible/host.orig

# configure host so it will run with localhost
echo "localhost ansible_connection=local" | sudo tee /etc/ansible/hosts
