#!/bin/bash

# GIT MAGIC
git stash
git stash drop
git pull

echo "> Scripts home dir is:"
echo $SCRIPTZ_HOME_DIR

# copy files to the home directory.
echo "> Copying dot files to home directory"
cp -rpf $SCRIPTZ_HOME_DIR/dotFiles/. $HOME

echo "> Adding execute privileges to scripts dir."
chmod -R 755 $SCRIPTZ_HOME_DIR/scripts/

# init bash rc files.
echo "> Sourcing .bashrc"
exec bash
